accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('logout/', views.LogOutView.as_view(), name="LogOutView"),
    path('login/', views.LogInView.as_view(), name="LogInView"),
    path('signup/', views.HandleSignUp.as_view(), name="HandleSignUp"),
    path('apply/', views.ApplyView.as_view(), name="ApplyView"),
    path('manage-application/', views.ManageApplicationView.as_view(), name="ManageApplicationView"),
    path('manage-uuid/', views.SignUpWithUUID.as_view(), name="SignUpWithUUID"),
    path('new-signup/', views.SignUpView.as_view(), name="SignUpView"),
    path('download/', views.DownloadFileView.as_view(), name="DownloadFileView"),
]
# 6333fbdc-4dbe-11ec-96da-3b9900e494a4

course/urls.py
from django.urls import path
from . import views

app_name="course"

urlpatterns = [
    path('', views.HomeView.as_view(), name="HomeView"),
    path('contact/', views.ContactView.as_view(), name="ContactView"),
    path('about-us/', views.AboutView.as_view(), name="AboutView"),
    path('admin-area/', views.AdminAreaView.as_view(), name="AdminAreaView"),
    path('admin-complain/', views.AdminComplainView.as_view(), name="AdminComplainView"),
    path('admin-warning/', views.AdminWarningView.as_view(), name="AdminWarningView"),
    path('student-area/', views.StudentAreaView.as_view(), name="StudentAreaView"),
    path('instructor-area/', views.InstructorAreaView.as_view(), name="InstructorAreaView"),
    path('manage-class/', views.ManageClassView.as_view(), name="ManageClassView"),
    path('manage-complain/', views.ManageComplainView.as_view(), name="ManageComplainView"),
    path('manage-warning/', views.ManageWarningView.as_view(), name="ManageWarningView"),
    path('create-semester/', views.CreateSemesterView.as_view(), name="CreateSemesterView"),
    path('deactivate-semester/', views.DeavtivateSemesterView.as_view(), name="DeavtivateSemesterView"),
    path('create-class/', views.CreateClassView.as_view(), name="CreateClassView"),
    path('remove-class/', views.RemoveClassView.as_view(), name="RemoveClassView"),
    path('class-detail/', views.CourseDetailView.as_view(), name="CourseDetailView"),
    path('class-detail-instructor/', views.InstructorCourseDetailView.as_view(), name="InstructorCourseDetailView"),
    path('manage-review/', views.ManageReviewView.as_view(), name="ManageReviewView"),
    path('manage-grade/', views.ManageGradeView.as_view(), name="ManageGradeView"),
    path('recieved-warnings/', views.RecievedWarningsView.as_view(), name="RecievedWarningsView"),
    path('classes/', views.StudentCartView.as_view(), name="StudentCartView"),
    path('enroll-requests/', views.EnrollRequestView.as_view(), name="EnrollRequestView"),
]

cunyzero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('course.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/forms.py
from django.forms import ModelForm
from django import forms

from course.models import Class, Semester
from course.widgets import CustomDatePickerInput, CustomTimePickerInput

# Create the form class.

class ClassForm(ModelForm):
    
    class Meta:
        model = Class
        exclude = ['enrolled_by','start_date','end_date','start_time','end_time', 'semester', 'cancelled']

class SemesterForm(ModelForm):
    class Meta:
        model = Semester
        exclude = ['']

course/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models.query_utils import Q
from django.http.response import Http404, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse
from django.views.generic import View
from accounts.models import Application, Grade, Profile
from course.forms import ClassForm, SemesterForm
from course.models import Class, ClassRequest, Complain, Review, Semester, ShoppingCart, TabooWord, Warning
import datetime
from course.utils import time_to_timestamp

# Create your views here.


class HomeView(View):
    def get(self, request):
        return render(request, 'course/home.html')

class ContactView(View):
    def get(self, request):
        return render(request, 'course/contactus.html')

class AboutView(View):
    def get(self, request):
        return render(request, 'course/about_us.html')

class AdminAreaView(View):
    def get(self, request):
        if not request.user.is_staff:
            return HttpResponseRedirect(reverse("course:HomeView"))

        pending_students = Application.objects.filter(role="std", approved=False, rejected=False)
        pending_instructors = Application.objects.filter(role="ins", approved=False, rejected=False)
        class_form = ClassForm(request.POST)
        # semester_form = SemesterForm()
        context = {"pending_instructors": pending_instructors, "pending_students": pending_students, "class_form": class_form}
        return render(request, 'course/admin-area.html', context)

class AdminComplainView(View):
    def get(self, request):
        if not request.user.is_staff:
            return HttpResponseRedirect(reverse("course:HomeView"))

        recieved_complains = Complain.objects.filter(action_taken = False)

        context = {"recieved_complains": recieved_complains}
        return render(request, 'course/admin-complains.html', context)

class AdminWarningView(View):
    def get(self, request):
        if not request.user.is_staff:
            return HttpResponseRedirect(reverse("course:HomeView"))

        students = Profile.objects.filter(role="std")
        instructors = Profile.objects.filter(role="ins")
        recieved_warnings = Warning.objects.filter(deactivated = False)

        context = {"recieved_warnings": recieved_warnings, "students": students, "instructors": instructors}
        return render(request, 'course/admin-warnings.html', context)


class StudentAreaView(View):
    def get(self, request):
        profile = request.user.profile
        if not profile.role == "std":
            return HttpResponseRedirect(reverse("course:HomeView"))
        enrolled_class_ids = [_class.id for _class in profile.get_current_classes]
        available_classes = Class.objects.filter(~Q(id__in=enrolled_class_ids))
        available_classes = [_class for _class in available_classes if _class.is_active]
        context = {"available_classes": available_classes}
        return render(request, 'course/student-area.html', context)

class InstructorAreaView(View):
    def get(self, request):
        profile = request.user.profile
        if not profile.role == "ins":
            return HttpResponseRedirect(reverse("course:HomeView"))
        return render(request, 'course/instructor-area.html')

class ManageClassView(View):
    def post(self, request):
        if not request.user.profile.role == "std":
            return HttpResponseRedirect(reverse("course:HomeView"))
        class_id = request.POST.get('class_id', None)
        action = request.POST.get('action', None)
        class_instance = get_object_or_404(Class, id=class_id)
        if action == "drop":
            class_instance.enrolled_by.remove(request.user.profile)
            messages.success(request, "Class Dropped")
        elif action == "enroll":
            """Add's class to cart. Enroll is at StudentCartView"""
            cart, created = ShoppingCart.objects.get_or_create(user=request.user.profile)
            cart.courses.add(class_instance)
            messages.success(request, "Class added to the cart.")

            # if not class_instance.quota <= len(class_instance.enrolled_by.all()):
            #     if not len(request.user.profile.get_current_classes) >= 4:
            #         conflict = False
            #         for enrolled_class in request.user.profile.get_current_classes:
            #             start_time = time_to_timestamp(enrolled_class.start_time)
            #             end_time = time_to_timestamp(enrolled_class.end_time)
            #             new_start_time = time_to_timestamp(class_instance.start_time)
            #             new_end_time = time_to_timestamp(class_instance.end_time)
            #             if (start_time < new_end_time and new_start_time < end_time):
            #                 conflict = True
            #         if not conflict:
            #             class_instance.enrolled_by.add(request.user.profile)
            #             class_instance.save()
            #             messages.success(request, "Class Enrolled")
            #         else:
            #             messages.error(request, "There's a time conflict between classes.")
            #     else:
            #         messages.error(request, "Max Class Enroll Limit Reached")
            # else:
            #     messages.error(request, "Class is full.")
        return HttpResponseRedirect(reverse("course:StudentAreaView"))

class RemoveClassView(View):
    def post(self, request):
        semester_id = request.POST.get('semester_id', None)
        class_id = request.POST.get('class_id', None)

        class_instance = get_object_or_404(Class, id=class_id)
        class_instance.delete()
        # semester_instance = get_object_or_404(Semester, id=semester_id)
        # semester_instance.classes.remove(class_instance)
        # semester_instance.save()

        messages.success(request, f"Class Removed")
        return HttpResponseRedirect(reverse("course:AdminAreaView"))


class ManageComplainView(View):
    def get(self, request):
        # if not request.user.is_staff:
        #     return HttpResponseRedirect(reverse("course:HomeView"))

        students = Profile.objects.filter(role="std")
        instructors = Profile.objects.filter(role="ins")
        context = {"students": students, "instructors": instructors}
        return render(request, 'course/complain.html', context)

    def post(self, request):
        # if not request.user.is_staff:
        #     return HttpResponseRedirect(reverse("course:HomeView"))

        complained_instructor = request.POST.get("complained_instructor", None)
        complained_user = request.POST.get("complained_user", None)
        complain_message = request.POST.get("complain_message", None)
        complain_id = request.POST.get("complain_id", None)
        action = request.POST.get("action", None)
        for_user = None
        print(action)

        if action == "resolved":
            complain = get_object_or_404(Complain, id = complain_id)
            complain.action_taken = True
            complain.save()
            messages.success(request, "Complain resolved successfully")
            return HttpResponseRedirect(reverse("course:AdminComplainView"))
        elif action == "create":
            if complained_instructor and complained_user:
                messages.error(request, "Select only student or instructor at a time!")
                return HttpResponseRedirect(reverse("course:ManageComplainView"))

            if complained_user:
                for_user = get_object_or_404(User, username = complained_user)
            elif complained_instructor:
                for_user = get_object_or_404(User, username = complained_instructor)

            Complain.objects.create(
                message = complain_message,
                by_profile = request.user.profile,
                for_profile = for_user.profile
            )
            messages.success(request, "Complain Submited Successfully")

        return HttpResponseRedirect(reverse("course:HomeView"))

class ManageWarningView(View):
    def post(self, request):
        if not request.user.is_staff:
            return HttpResponseRedirect(reverse("course:HomeView"))

        warning_instructor = request.POST.get("warning_instructor", None)
        warning_user = request.POST.get("warning_user", None)
        warning_message = request.POST.get("warning_message", None)
        warning_reason = request.POST.get("warning_reason", None)
        warning_id = request.POST.get("warning_id", None)
        action = request.POST.get("action", None)
        for_user = None
        print(action)

        if action == "delete":
            warning = get_object_or_404(Warning, id = warning_id)
            warning.deactivated = True
            warning.save()
            messages.success(request, "Warning Removed Successfully.")
        if action == "issue":
            if warning_instructor and warning_user:
                messages.error(request, "Select only student or instructor at a time!")
                return HttpResponseRedirect(reverse("course:ManageComplainView"))

            if warning_user:
                for_user = get_object_or_404(User, username = warning_user)
            elif warning_instructor:
                for_user = get_object_or_404(User, username = warning_instructor)

            semesters = Semester.objects.filter(deactivated=False)
            active_semester = [semester for semester in semesters if semester.is_active]
            if active_semester:
                active_semester = active_semester[0]
            else:
                active_semester = None

            Warning.objects.create(
                profile = for_user.profile,
                message = warning_message,
                reason = warning_reason,
                semester = active_semester,
            )

templates/course/admin-area.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
<style>
    #showcase{
        background: url("{% static 'images/admin-area.jpg' %}") no-repeat;
        background-size: 100%;
        background-position: center;

        display: flex;
        justify-content: center;
        align-items: center;
    }
    #showcase .title{
        font-size: 5rem;
        font-weight: bolder;
        color: #fff;
        text-shadow: 0px 3px 5px black;
    }
    .pending-table{
        min-width: 300px;
    }
    .active-semester{
        border: 2px solid rgba(80, 186, 52, 0.8);
        border-radius: 10px;
        background-color: rgba(89, 235, 52, 0.3);
        height: 350px;
    }
    .add-class-btn{
        height: 50px;
        width: 100%;
        background-color: #ffc300d6;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 2rem;
        color: #fff;
        cursor: pointer;
    }
    .table-active{
        background-color: rgba(89, 235, 52, 0.3);
    }
</style>
{% endblock ExtraCss %}


{% block content %}


    <section id="showcase" class="w-100 mb-5">
        <h1 class="title">Admin Area</h1>
    </section>

    <section class="mx-5">
        <div class="row">
            <div class="col">
                <h2 class="text-center">Pending Instructors</h2>
                <table class="table table-striped table-dark pending-table">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                        <th scope="col">Document</th>
                        <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for application in pending_instructors %}
                        <tr>
                            <th scope="row">{{application.id}}</th>
                            <td>{{application.first_name}}</td>
                            <td>{{application.last_name}}</td>
                            <td>
                                <a href="{% url 'accounts:DownloadFileView' %}?file={{application.document.name}}">Download</a>
                            </td>
                            <td>
                                <form action="{% url 'accounts:ManageApplicationView' %}" method="POST" class="mb-2">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{application.id}}" name="application_id">
                                    <input type="hidden" value="approve" name="action">
                                    <input type="submit" value="Approve" class="btn btn-sm btn-success">
                                </form>
                                <form action="{% url 'accounts:ManageApplicationView' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{application.id}}" name="application_id">
                                    <input type="hidden" value="reject" name="action">
                                    <input type="submit" value="Reject" class="btn btn-sm btn-danger">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col">
                <h2 class="text-center">Pending Students</h2>
                <table class="table table-striped table-dark pending-table">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                        <th scope="col">Document</th>
                        <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for application in pending_students %}
                        <tr>
                            <th scope="row">{{application.id}}</th>
                            <td>{{application.first_name}}</td>
                            <td>{{application.last_name}}</td>
                            <td>
                                <a href="{% url 'accounts:DownloadFileView' %}?file={{application.document.name}}">Download</a>
                            </td>
                            <td>
                                <form action="{% url 'accounts:ManageApplicationView' %}" method="POST" class="mb-2">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{application.id}}" name="application_id">
                                    <input type="hidden" value="approve" name="action">
                                    <input type="submit" value="Approve" class="btn btn-sm btn-success">
                                </form>
                                <form action="{% url 'accounts:ManageApplicationView' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{application.id}}" name="application_id">
                                    <input type="hidden" value="reject" name="action">
                                    <input type="submit" value="Reject" class="btn btn-sm btn-danger">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>


    <section class="container mt-5">
        <div class="">
            <h1>Class Setup</h1>
            <br>

            {% if active_semester %}
                <div class="active-semester">
                    <div class="p-5">
                        <h3 class="text-light fs-2 lead mb-3" style="text-shadow: 0px 0px 3px rgba(0,0,0,0.8);">
                        {% if active_semester.get_status == "Setup" %}
                            Semester is in Setup Period
                        {% elif active_semester.get_status == "Registration" %}
                            Semester is in Registration Period
                        {% elif active_semester.get_status == "Running" %}
                            Semester is Running
                        {% elif active_semester.get_status == "Grading" %}
                            Semester is in Grading Period
                        {% else %}
                            There's an active Semester.
                        {% endif %}
                            
                        </h3>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Start Date</th>
                                    <th scope="col">End Date</th>
                                    <th scope="col">Setup Date</th>
                                    <th scope="col">Registration Period</th>
                                    <th scope="col">Running Period</th>
                                    <th scope="col">Grading Period</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">{{active_semester.id}}</th>
                                    <td>{{active_semester.start_date}}</td>
                                    <td>{{active_semester.end_date}}</td>
                                    <td>{{active_semester.setup_period}}</td>
                                    <td>{{active_semester.registration_period}}</td>
                                    <td>{{active_semester.running_period}}</td>
                                    <td>{{active_semester.grading_period}}</td>
                                </tr>
                            </tbody>
                        </table>

                        <button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#deactivate-semester-form">Deactivate</button>

                        <div class="modal fade" id="deactivate-semester-form" tabindex="-1" aria-labelledby="deactivate-semester-form" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title text-dark" id="deactivate-semester-form-label">Are You Sure!</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body text-dark">
                                        <form action="{% url 'course:DeavtivateSemesterView' %}" method="POST" class="mb-2">
                                            {% csrf_token %}
                                            <input type="hidden" value="{{active_semester.id}}" name="semester_id">
                                            <input type="submit" value="Deactivate" class="btn btn-sm btn-danger">
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                {% include "template-parts/semester-form.html" %}
            {% endif %}

            <section class="mt-5">
                <h5>Semester Classes:</h5>
                <br>
                <div>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Instructor</th>
                            <th scope="col">Schedule</th>
                            <th scope="col">Timing</th>
                            <th scope="col">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for class in active_semester.get_classes %}
                                <tr class="{% if class.currently_active %} table-active {% endif %}">
                                    <th scope="row">{{class.id}}</th>
                                    <td style="max-width: 200px;">{{class.title}}</td>
                                    <td>{{class.instructor}}</td>
                                    <td>{{class.start_date}}-{{class.end_date}}</td>
                                    <td>{{class.start_time}} to {{class.end_time}}</td>
                                    <td>
                                    {% if active_semester.get_status == "Setup" %}
                                        <form action="{% url 'course:RemoveClassView' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="class_id" value="{{class.id}}">
                                            <input type="hidden" name="semester_id" value="{{active_semester.id}}">
                                            <input type="submit" value="Remove" class="btn btn-sm btn-danger">
                                        </form>
                                    {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% if active_semester.get_status == "Setup" %}
                        <div class="add-class-btn" data-bs-toggle="modal" data-bs-target="#add-class-form">
                            +
                        </div>

                        <div class="modal fade" id="add-class-form" tabindex="-1" aria-labelledby="add-class-form" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title text-dark" id="add-class-form-label">Add Class Form</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body text-dark">
                                        {% include "template-parts/class-form.html" %}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </section>
            {% comment %} {{class_form|crispy}} {% endcomment %}
        </div>
    </section>



{% endblock content %}

{% block ExtraJs %}
{% endblock ExtraJs %}

templates/course/instructor-area.html
{% extends 'base.html' %}

{% load static %}

{% block ExtraCss %}
<style>
    #showcase{
        background: url("{% static 'images/admin-area.jpg' %}") no-repeat;
        background-size: 100%;
        background-position: center;

        display: flex;
        justify-content: center;
        align-items: center;
    }
    #showcase .title{
        font-size: 5rem;
        font-weight: bolder;
        color: #fff;
        text-shadow: 0px 3px 5px black;
    }
    .pending-table{
        min-width: 300px;
    }
</style>
{% endblock ExtraCss %}


{% block content %}


    <section id="showcase" class="w-100 mb-5">
        <h1 class="title">Instructor Area</h1>
    </section>

    <section class="mx-5">
        <div class="row">
            <div class="col">
            <section class="mt-5">
                <h5>Assigned Classes:</h5>
                <br>
                <div>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Instructor</th>
                            <th scope="col">Schedule</th>
                            <th scope="col">Timing</th>
                            <th scope="col">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for class in request.user.profile.get_assigned_classes %}
                                <tr class="{% if class.currently_active %} table-active {% endif %}">
                                    <th scope="row">{{class.id}}</th>
                                    <td style="max-width: 200px;"><a href="{% url 'course:InstructorCourseDetailView' %}?id={{class.id}}">{{class.title}}</a></td>
                                    <td>{{class.instructor}}</td>
                                    <td>{{class.start_date}}-{{class.end_date}}</td>
                                    <td>{{class.start_time}} to {{class.end_time}}</td>
                                    <td>
                                        <form action="{% url 'course:RemoveClassView' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="class_id" value="{{class.id}}">
                                            <input type="hidden" name="semester_id" value="{{active_semester.id}}">
                                            <input type="submit" value="Remove" class="btn btn-sm btn-danger">
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </section>
            </div>
        </div>
    </section>


    <section class="mx-5 mt-5">
        <div class="text-center">
            <a href="{% url 'course:ManageComplainView' %}" class="btn btn-lg btn-danger">Complain</a>
        </div>
    </section>



{% endblock content %}

{% block ExtraJs %}
{% endblock ExtraJs %}