account/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('logout/', views.LogOutView.as_view(), name="LogOutView"),
    path('login/', views.LogInView.as_view(), name="LogInView"),
    path('signup/', views.SignUpView.as_view(), name="SignUpView"),

]

accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('logout/', views.LogOutView.as_view(), name="LogOutView"),
    path('login/', views.LogInView.as_view(), name="LogInView"),
    path('signup/', views.HandleSignUp.as_view(), name="HandleSignUp"),
    path('apply/', views.ApplyView.as_view(), name="ApplyView"),
    path('manage-application/', views.ManageApplicationView.as_view(), name="ManageApplicationView"),
    path('manage-uuid/', views.SignUpWithUUID.as_view(), name="SignUpWithUUID"),
    path('new-signup/', views.SignUpView.as_view(), name="SignUpView"),
    path('download/', views.DownloadFileView.as_view(), name="DownloadFileView"),
]
# 6333fbdc-4dbe-11ec-96da-3b9900e494a4

course/urls.py
from django.urls import path
from . import views

app_name="course"

urlpatterns = [
    path('', views.HomeView.as_view(), name="HomeView"),
    path('contact/', views.ContactView.as_view(), name="ContactView"),
    path('about-us/', views.AboutView.as_view(), name="AboutView"),
    path('admin-area/', views.AdminAreaView.as_view(), name="AdminAreaView"),
    path('admin-complain/', views.AdminComplainView.as_view(), name="AdminComplainView"),
    path('admin-warning/', views.AdminWarningView.as_view(), name="AdminWarningView"),
    path('student-area/', views.StudentAreaView.as_view(), name="StudentAreaView"),
    path('instructor-area/', views.InstructorAreaView.as_view(), name="InstructorAreaView"),
    path('manage-class/', views.ManageClassView.as_view(), name="ManageClassView"),
    path('manage-complain/', views.ManageComplainView.as_view(), name="ManageComplainView"),
    path('manage-warning/', views.ManageWarningView.as_view(), name="ManageWarningView"),
    path('create-semester/', views.CreateSemesterView.as_view(), name="CreateSemesterView"),
    path('deactivate-semester/', views.DeavtivateSemesterView.as_view(), name="DeavtivateSemesterView"),
    path('create-class/', views.CreateClassView.as_view(), name="CreateClassView"),
    path('remove-class/', views.RemoveClassView.as_view(), name="RemoveClassView"),
    path('class-detail/', views.CourseDetailView.as_view(), name="CourseDetailView"),
    path('class-detail-instructor/', views.InstructorCourseDetailView.as_view(), name="InstructorCourseDetailView"),
    path('manage-review/', views.ManageReviewView.as_view(), name="ManageReviewView"),
    path('manage-grade/', views.ManageGradeView.as_view(), name="ManageGradeView"),
    path('recieved-warnings/', views.RecievedWarningsView.as_view(), name="RecievedWarningsView"),
    path('classes/', views.StudentCartView.as_view(), name="StudentCartView"),
    path('enroll-requests/', views.EnrollRequestView.as_view(), name="EnrollRequestView"),
]

cunyzero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('course.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
ROLES = (
    ('ins', "Instructor"),
    ('std', "Student"),
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    role = models.CharField(choices=ROLES, max_length=50)
    image = models.ImageField(upload_to='profile_pics/')

    def get_image(self):
        try:
            return self.image.url
        except:
            return ''

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

accounts/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from course.models import Class, Semester

# Create your models here.
ROLES = (
    ('ins', "Instructor"),
    ('std', "Student"),
)
    # GPA = models.FloatField(default=0.00)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    role = models.CharField(choices=ROLES, max_length=50)
    image = models.ImageField(upload_to='profile_pics/')
    suspended = models.BooleanField(default=False)
    GPA = models.FloatField(default=0.00)
    
    def __str__(self):
        return f"{self.user.username}-{self.role}-GPA:({self.get_gpa})"
    
    @property
    def get_image(self):
        try:
            return self.image.url
        except:
            return ''

    @property
    def get_enroll_requests(self):
        requests = []
        classes = Class.objects.filter(instructor__id = self.id)
        print(classes)
        for _class in classes:
            for request in _class.enroll_requests.all():
                requests.append(request)
        return requests

    @property
    def get_gpa(self):
        try:
            total_gpa = 0
            final_gpa = 0
            # print(self.grades.all())
            for grade in self.grades.all():
                total_gpa += float(grade.GPA)
            total_grades_given = len(self.grades.all())
            if total_grades_given:
                final_gpa = total_gpa/total_grades_given
            # print(final_gpa)
            return round(final_gpa,2)
        except:
            return 0

    @property
    def get_warnings(self):
        try:
            warnings = self.warnings_revieved.filter(deactivated=False)
        except:
            warnings = []
        return warnings

    @property
    def get_current_classes(self):
        try:
            enrolled_classes = self.enrolled_classes.all()
            active_enrolled_classes = [_class for _class in enrolled_classes if _class.is_active]
            return active_enrolled_classes
        except:
            return []

    @property
    def get_assigned_classes(self):
        try:
            assigned_classes = self.assigned_classes.all()
            active_assigned_classes = [_class for _class in assigned_classes if _class.is_active]
            return active_assigned_classes
        except:
            return []

    @property
    def is_special_registration(self):
        try:
            current_timestamp = datetime.datetime.now().timestamp()
            semesters = Semester.objects.filter(deactivated=False)
            active_semester = [semester for semester in semesters if semester.is_active]
            if active_semester:
                active_semester = active_semester[0]

            enrolled_classes = self.enrolled_classes.all()
            deactive_enrolled_classes = [_class for _class in enrolled_classes if not _class.is_active]
            
            special_period_timestamp = (active_semester.registration_period + datetime.timedelta(days=6)).timestamp()
            if deactive_enrolled_classes:
                if current_timestamp < special_period_timestamp:
                    return True
        except:
            return []

    @property
    def get_reviews(self):
        try:
            return self.reviews_given.all()
        except:
            return []

    @receiver(post_save, sender=User)
    def update_profile_signal(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
        instance.profile.save()
    
class Grade(models.Model):
    GPA = models.FloatField(default=0.00)
    by_instructor = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE, related_name="given_grades")
    to_student = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE, related_name="grades")
    refferring_class = models.ForeignKey("course.Class", on_delete=models.CASCADE, related_name="given_grades")

class Application(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    role = models.CharField(choices=ROLES, max_length=50)
    document = models.FileField(upload_to='applications/', blank=False)
    approved = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)
    uuid = models.OneToOneField("accounts.UserUniqueId", on_delete=models.CASCADE, related_name="application", null=True, blank=True)


class UserUniqueId(models.Model):
    uuid = models.CharField(max_length=500, null=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="unique_id", null=True, blank=True)
    expired = models.BooleanField(default=False)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    image = forms.ImageField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name','username','image', 'email', 'password1', 'password2')

accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from accounts.models import UserUniqueId

class SignUpForm(UserCreationForm):
    image = forms.ImageField()

    class Meta:
        model = User
        fields = ('username','image', 'email', 'password1', 'password2')
        
        
# class UserUniqueIdForm(ModelForm):
#     class Meta:
#         model = UserUniqueId
#         fields = ['uuid']
        
        
        
        
        

# Create the form class.

accounts/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http.response import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.urls import reverse
from django.views.generic.base import View
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
import uuid
import mimetypes
import os
from django.conf import settings
from .models import Application, UserUniqueId
from .forms import SignUpForm


# Create your views here.



class HandleSignUp(View):
    def get(self, request):
        _uuid = request.session.get("user_uuid", None)
        try:
            user_uuid_instance = UserUniqueId.objects.get(uuid = _uuid, expired = False)
        except:
            user_uuid_instance = None
        
        if _uuid and user_uuid_instance:
            form = SignUpForm()
            context = {'form': form}
            messages.success(request, "Please Continue Your SignUp.")
            return render(request, 'accounts/signup.html', context)
        else:
            return render(request, 'accounts/uuid_signup.html')




class SignUpWithUUID(View):

    def post(self, request):
        _uuid = request.POST.get('uuid', None)
        if _uuid:
            # form.save()
            user_uuid_instance = get_object_or_404(UserUniqueId, uuid = _uuid)
            # user_uuid_instance.expired = True
            # user_uuid_instance.save()
            request.session["user_uuid"] = user_uuid_instance.uuid
            return HttpResponseRedirect(reverse("accounts:HandleSignUp"))
        raise Http404()

class SignUpView(View):
    # def get(self, request):
    #     form = SignUpForm()
    #     context = {'form': form}
    #     return render(request, 'accounts/signup.html', context)

    def post(self, request):
        _uuid = request.session.get("user_uuid", None)

        try:
            user_uuid_instance = UserUniqueId.objects.get(uuid = _uuid, expired = False)
        except:
            user_uuid_instance = None

        if not _uuid or not user_uuid_instance:
            raise ValidationError("UUID is incorrect")

        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            # form.save()
            user = form.save()
            user.refresh_from_db()

            user.first_name = user_uuid_instance.application.first_name
            user.last_name = user_uuid_instance.application.last_name
            user.profile.image = form.cleaned_data.get('image')
            user.profile.role = user_uuid_instance.application.role

            user.profile.save()
            user.save()

            user_uuid_instance.user = user
            user_uuid_instance.expired = True
            user_uuid_instance.save()

            request.session.flush()

            login(request, user)
            return HttpResponseRedirect(reverse("course:HomeView"))
        context = {'form': form}
        return render(request, 'accounts/signup.html', context)


class LogOutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, "Successfully Logged Out.")
        return HttpResponseRedirect(reverse('course:HomeView'))


class LogInView(View):
    def get(self, request):
        if request.user.is_authenticated:
            messages.warning(request, "You are already logged in")
            return HttpResponseRedirect(reverse('course:HomeView'))
        form = AuthenticationForm()
        context = {'form' : form}
        return render(request,'accounts/login.html', context)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username,password = password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse('course:HomeView'))
        else:
            form = AuthenticationForm(request.POST)
            context = {'form' : form}
            return render(request,'accounts/login.html', context)


class ApplyView(View):
    def get(self, request):
        return render(request, 'accounts/apply.html')

    def post(self, request):
        document = request.FILES.get('document', None)
        role = request.POST.get('role', None)
        first_name = request.POST.get('first_name', None)
        last_name = request.POST.get('last_name', None)
        
        if document and role:
            Application.objects.create(
                first_name = first_name,
                last_name = last_name,
                document = document,
                role = role,
            )
            messages.success(request, "Application has been submited successfully.")
            return HttpResponseRedirect(reverse("course:HomeView"))
        messages.error(request, "Application form is not correct.")
        return render(request, 'accounts/apply.html')
    
class ManageApplicationView(View):

    def post(self, request):
        action = request.POST.get('action', None)
        application_id = request.POST.get('application_id', None)
        application = get_object_or_404(Application, id=application_id)
        user_uuid = None
        if action == "approve":
            user_uuid = UserUniqueId.objects.create(
                uuid = uuid.uuid1()
            )
            application.approved = True
            application.uuid = user_uuid
            application.rejected = False
            messages.success(request, f"Application has been {action}-{user_uuid.uuid}")
        elif action == "reject":
            application.approved = False
            application.rejected = True
            messages.success(request, f"Application has been Rejected")
        application.save()

        return HttpResponseRedirect(reverse("course:AdminAreaView"))



class DownloadFileView(View):
    def get(self, request):
        filename = request.GET.get('file', None)
        filepath = f'{settings.BASE_DIR}/media/{filename}'
        try:
            with open(filepath, 'rb') as _file:
                mime_type, _ = mimetypes.guess_type(filepath)
                response = HttpResponse(_file, content_type=mime_type)
                response['Content-Disposition'] = "attachment; filename=%s" % filename
                return response
        except FileNotFoundError:
            raise Http404()

templates/accounts/apply.html
{% extends 'base.html' %}

{% block ExtraCss %}

{% endblock ExtraCss %}

{% block content %}

<section class="container mt-5">
    <div class="card w-50 m-auto p-5">
        <div class="text-center mb-2">
            <h3>Apply Form</h3>
        </div>
        <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="text-center mb-4">
                <input type="text" name="first_name" placeholder="Enter First Name">
                <input type="text" name="last_name" placeholder="Enter Last Name">
            </div>
            <div class="form-check mx-auto">
                <input class="form-check-input" type="radio" name="role" id="role1" value="ins" checked>
                <label class="form-check-label" for="role1">
                    Apply For Instructor
                </label>
                </div>
                <div class="form-check">
                <input class="form-check-input" type="radio" name="role" id="role2" value="std">
                <label class="form-check-label" for="role2">
                    Apply For Student
                </label>
            </div>
            <br>
            <input type="file" name="document" required>
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</section>

{% endblock content %}

{% block ExtraJs %}

{% endblock ExtraJs %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block ExtraCss %}
<style>
    form ul{
        list-style: none;
    }
</style>
{% endblock ExtraCss %}

{% block content %}

<section class="container mt-5">
    <div class="form-cont card text-center p-5">
        <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% comment %} {{form.as_p}} {% endcomment %}
            {% for field in form %}
                <p>
                {{ field.label_tag }}<br>
                {{ field }}
                <br>
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
                </p>
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</section>

{% endblock content %}

{% block ExtraJs %}

{% endblock ExtraJs %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block ExtraCss %}
<style>
    form ul{
        list-style: none;
    }
</style>
{% endblock ExtraCss %}

{% block content %}

<section class="container mt-5">
    <div class="form-cont card text-center p-5">
        <h1 class="lead fs-1 mb-5">Continue SignUp</h1>
        <form action="{% url 'accounts:SignUpView' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <p>
                {{ field.label_tag }}<br>
                {{ field }}
                <br>
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
                </p>
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</section>

{% endblock content %}

{% block ExtraJs %}

{% endblock ExtraJs %}

templates/accounts/uuid_signup.html
{% extends 'base.html' %}

{% block ExtraCss %}
<style>
    form ul{
        list-style: none;
    }
</style>
{% endblock ExtraCss %}

{% block content %}

<section class="container mt-5">
    <div class="form-cont card text-center p-5">
        <h1 class="lead fs-1 mb-5">SignUp</h1>
        <form action="{% url 'accounts:SignUpWithUUID' %}" method="POST">
            {% csrf_token %}
            <input class="p-2 mb-4" type="text" name="uuid" placeholder="Enter Your UUID" required>
            <br>
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</section>

{% endblock content %}

{% block ExtraJs %}

{% endblock ExtraJs %}