course/urls.py
from django.urls import path
from . import views

app_name="course"

urlpatterns = [
    path('', views.HomeView.as_view(), name="HomeView"),
    path('contact/', views.ContactView.as_view(), name="ContactView"),
    path('about-us/', views.AboutView.as_view(), name="AboutView"),
    path('admin-area/', views.AdminAreaView.as_view(), name="AdminAreaView"),
    path('admin-complain/', views.AdminComplainView.as_view(), name="AdminComplainView"),
    path('admin-warning/', views.AdminWarningView.as_view(), name="AdminWarningView"),
    path('student-area/', views.StudentAreaView.as_view(), name="StudentAreaView"),
    path('instructor-area/', views.InstructorAreaView.as_view(), name="InstructorAreaView"),
    path('manage-class/', views.ManageClassView.as_view(), name="ManageClassView"),
    path('manage-complain/', views.ManageComplainView.as_view(), name="ManageComplainView"),
    path('manage-warning/', views.ManageWarningView.as_view(), name="ManageWarningView"),
    path('create-semester/', views.CreateSemesterView.as_view(), name="CreateSemesterView"),
    path('deactivate-semester/', views.DeavtivateSemesterView.as_view(), name="DeavtivateSemesterView"),
    path('create-class/', views.CreateClassView.as_view(), name="CreateClassView"),
    path('remove-class/', views.RemoveClassView.as_view(), name="RemoveClassView"),
    path('class-detail/', views.CourseDetailView.as_view(), name="CourseDetailView"),
    path('class-detail-instructor/', views.InstructorCourseDetailView.as_view(), name="InstructorCourseDetailView"),
    path('manage-review/', views.ManageReviewView.as_view(), name="ManageReviewView"),
    path('manage-grade/', views.ManageGradeView.as_view(), name="ManageGradeView"),
    path('recieved-warnings/', views.RecievedWarningsView.as_view(), name="RecievedWarningsView"),
    path('classes/', views.StudentCartView.as_view(), name="StudentCartView"),
    path('enroll-requests/', views.EnrollRequestView.as_view(), name="EnrollRequestView"),
]

cunyzero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('course.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/template-parts/class-form.html
{% load crispy_forms_tags %}

<form action="{% url 'course:CreateClassView' %}" method="POST" class="mb-2">
    {% csrf_token %}
    <input type="hidden" name="semester_id" value="{{active_semester.id}}">
    <div class="row mb-3">
        <div class="col-6">
            <label for="start-date" class="form-label">Start Date:</label>
            <div>
                <input type="date" class="form-control" name="start_date" id="start-date" required>
            </div>
        </div>

        <div class="col-6">
            <label for="end-date" class="form-label">End Date:</label>
            <div>
                <input type="date" class="form-control" name="end_date" id="end-date" required>
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <p>Timing</p>
        <div class="input-group mb-3">
            <input type="time" name="start_time" id="start-time" class="form-control" required>
            <span class="input-group-text">to</span>
            <input type="time" name="end_time" id="end-time" class="form-control" required>
        </div>
    </div>
    {{class_form|crispy}}
    <br>
    <input type="submit" value="Add Class" class="btn btn-success">
</form>

templates/template-parts/review_section.html
<style>
    .total-like-user-main a {
        display: inline-block;
        margin: 0 -17px 0 0;
    }
    .total-like {
        border: 1px solid;
        border-radius: 50px;
        display: inline-block;
        font-weight: 500;
        height: 34px;
        line-height: 33px;
        padding: 0 13px;
        vertical-align: top;
    }
    .restaurant-detailed-ratings-and-reviews hr {
        margin: 0 -24px;
    }
    .graph-star-rating-header .star-rating {
        font-size: 17px;
    }
    .progress {
        background: #f2f4f8 none repeat scroll 0 0;
        border-radius: 0;
        height: 30px;
    }
    .rating-list {
        display: inline-flex;
        margin-bottom: 15px;
        width: 100%;
    }
    .rating-list-left {
        height: 16px;
        line-height: 29px;
        width: 10%;
    }
    .rating-list-center {
        width: 80%;
    }
    .rating-list-right {
        line-height: 29px;
        text-align: right;
        width: 10%;
    }
    .restaurant-slider-pics {
        bottom: 0;
        font-size: 12px;
        left: 0;
        z-index: 999;
        padding: 0 10px;
    }
    .restaurant-slider-view-all {
        bottom: 15px;
        right: 15px;
        z-index: 999;
    }
    .offer-dedicated-nav .nav-link.active,
    .offer-dedicated-nav .nav-link:hover,
    .offer-dedicated-nav .nav-link:focus {
        border-color: #3868fb;
        color: #3868fb;
    }
    .offer-dedicated-nav .nav-link {
        border-bottom: 2px solid #fff;
        color: #000000;
        padding: 16px 0;
        font-weight: 600;
    }
    .offer-dedicated-nav .nav-item {
        margin: 0 37px 0 0;
    }
    .restaurant-detailed-action-btn {
        margin-top: 12px;
    }
    .restaurant-detailed-header-right .btn-success {
        border-radius: 3px;
        height: 45px;
        margin: -18px 0 18px;
        min-width: 130px;
        padding: 7px;
    }
    .text-black {
        color: #000000;
    }
    .icon-overlap {
        bottom: -23px;
        font-size: 74px;
        opacity: 0.23;
        position: absolute;
        right: -32px;
    }
    .menu-list img {
        width: 41px;
        height: 41px;
        object-fit: cover;
    }
    .restaurant-detailed-header-left img {
        width: 88px;
        height: 88px;
        border-radius: 3px;
        object-fit: cover;
        box-shadow: 0 .125rem .25rem rgba(0, 0, 0, .075)!important;
    }
    .reviews-members .media .mr-3 {
        width: 56px;
        height: 56px;
        object-fit: cover;
    }
    .rounded-pill {
        border-radius: 50rem!important;
    }
    .total-like-user {
        border: 2px solid #fff;
        height: 34px;
        box-shadow: 0 .125rem .25rem rgba(0, 0, 0, .075)!important;
        width: 34px;
    }
    .total-like-user-main a {
        display: inline-block;
        margin: 0 -17px 0 0;
    }
    .total-like {
        border: 1px solid;
        border-radius: 50px;
        display: inline-block;
        font-weight: 500;
        height: 34px;
        line-height: 33px;
        padding: 0 13px;
        vertical-align: top;
    }
    .restaurant-detailed-ratings-and-reviews hr {
        margin: 0 -24px;
    }
    .graph-star-rating-header .star-rating {
        font-size: 17px;
    }
    .progress {
        background: #f2f4f8 none repeat scroll 0 0;
        border-radius: 0;
        height: 30px;
    }
    .rating-list {
        display: inline-flex;
        margin-bottom: 15px;
        width: 100%;
    }
    .rating-list-left {
        height: 16px;
        line-height: 29px;
        width: 10%;
    }
    .rating-list-center {
        width: 80%;
    }
    .rating-list-right {
        line-height: 29px;
        text-align: right;
        width: 10%;
    }
    .restaurant-slider-pics {
        bottom: 0;
        font-size: 12px;
        left: 0;
        z-index: 999;
        padding: 0 10px;
    }
    .restaurant-slider-view-all {
        bottom: 15px;
        right: 15px;
        z-index: 999;
    }

    .progress {
        background: #f2f4f8 none repeat scroll 0 0;
        border-radius: 0;
        height: 30px;
    }
</style>


<div class="mx-5">
<div class="col-md-12">
    <div class="offer-dedicated-body-left">
        <div class="tab-content" id="pills-tabContent">
                <div class="bg-white rounded shadow-sm p-4 mb-4 restaurant-detailed-ratings-and-reviews">
                    <h5 class="mb-1">All Ratings and Reviews</h5>
                    {% for review in reviews %}
                    <div class="reviews-members pt-4 pb-4">
                        <div class="media">
                            <a href="#"><img alt="Generic placeholder image" src="{{review.by_profile.get_image}}" class="mr-3 rounded-pill"></a>
                            <div class="media-body">
                                <div class="reviews-members-header">
                                    <span class="star-rating float-right">
                                        {% with review.get_stars as stars %}
                                            {% for i in '12345'|make_list %}
                                                {% if stars >= forloop.counter %}
                                                    <i class="fa fa-star text-primary"></i>
                                                {% else %}
                                                    <i class="fa fa-star text-muted"></i>
                                                {% endif %}
                                            {% endfor %}
                                        {% endwith %}
                                        {% comment %} <a href="#"><i class="fas fa-star active"></i></a>
                                        <a href="#"><i class="fas fa-star active"></i></a>
                                        <a href="#"><i class="fas fa-star active"></i></a>
                                        <a href="#"><i class="fas fa-star active"></i></a>
                                        <a href="#"><i class="fas fa-star"></i></a> {% endcomment %}
                                    </span>
                                    <h6 class="mb-1">{{review.by_profile.user.username}}</h6>
                                    <p class="text-gray">{{review.date_created}}</p>
                                </div>
                                <div class="reviews-members-body">
                                    <p>{{review.body}}</p>
                                </div>
                                {% if review.by_profile.user == request.user %}
                                    <form action="{% url 'course:ManageReviewView' %}" method="POST" class="float-right mb-4">
                                        {% csrf_token %}
                                        <input type="hidden" value="{{class.id}}" name="class_id">
                                        <input type="hidden" value="{{review.id}}" name="review_id">
                                        <input type="hidden" value="delete" name="action">
                                        <button class="btn btn-danger btn-sm" type="submit">Remove</button>
                                    </form>
                                {% endif %}
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                </div>

                {% if request.user.is_authenticated and active_semester.get_status == "Running" %}
                <div class="bg-white rounded shadow-sm p-4 mb-5 rating-review-select-page">
                    <h5 class="mb-4">Leave Review</h5>

                    <form action="{% url 'course:ManageReviewView' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{class.id}}" name="class_id">
                        <input type="hidden" value="add" name="action">

                        <div class="form-group">
                            <label for="stars">Stars</label>
                            <select name="stars" id="stars">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Your Comment</label>
                            <textarea class="form-control" name="comment_body"></textarea>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-sm" type="submit"> Submit Comment </button>
                        </div>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>

templates/template-parts/semester-form.html
<form action="{% url 'course:CreateSemesterView' %}" method="POST">
    {% csrf_token %}
    <h5>Semester Settings</h5>
    <div class="row p-2">
        <div class="col-6">
            <label for="start-date" class="form-label">Start Date:</label>
            <div>
                <input type="date" name="start_date" id="start-date" class="form-control my-2 w-50" required>
            </div>
        </div>

        <div class="col-6">
            <label for="end-date" class="form-label">End Date:</label>
            <div>
                <input type="date" name="end_date" id="end-date" class="form-control my-2 w-50" required>
            </div>
        </div>
    </div>

    <div class="p-2">
        <label for="setup-date" class="form-label">Setup Period End Date:</label>
        <div>
            <input type="date" name="setup_period_date" id="setup-date" class="form-control my-2 w-50" required>
            <input type="time" name="setup_period_time" class="form-control my-2 w-50" required>
        </div>
    </div>

    <div class="p-2">
        <label for="registration-date" class="form-label">Registration Period End Date:</label>
        <div>
            <input type="date" name="registration_period_date" id="registration-date" class="form-control my-2 w-50" required>
            <input type="time" name="registration_period_time" class="form-control my-2 w-50" required>
        </div>
    </div>

    <div class="p-2">
        <label for="running-date" class="form-label">Running Period End Date:</label>
        <div>
            <input type="date" name="running_period_date" id="running-date" class="form-control my-2 w-50" required>
            <input type="time" name="running_period_time" class="form-control my-2 w-50" required>
        </div>
    </div>

    <div class="p-2">
        <label for="graduate-date" class="form-label">Graduation Period End Date:</label>
        <div>
            <input type="date" name="grading_period_date" id="graduate-date" class="form-control my-2 w-50" required>
            <input type="time" name="grading_period_time" class="form-control my-2 w-50" required>
        </div>
    </div>

    <div class="p-2">
        <input type="submit" value="Create Semester" class="btn btn-primary">
    </div>
</form>