account/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('logout/', views.LogOutView.as_view(), name="LogOutView"),
    path('login/', views.LogInView.as_view(), name="LogInView"),
    path('signup/', views.SignUpView.as_view(), name="SignUpView"),

]

accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('logout/', views.LogOutView.as_view(), name="LogOutView"),
    path('login/', views.LogInView.as_view(), name="LogInView"),
    path('signup/', views.HandleSignUp.as_view(), name="HandleSignUp"),
    path('apply/', views.ApplyView.as_view(), name="ApplyView"),
    path('manage-application/', views.ManageApplicationView.as_view(), name="ManageApplicationView"),
    path('manage-uuid/', views.SignUpWithUUID.as_view(), name="SignUpWithUUID"),
    path('new-signup/', views.SignUpView.as_view(), name="SignUpView"),
    path('download/', views.DownloadFileView.as_view(), name="DownloadFileView"),
]
# 6333fbdc-4dbe-11ec-96da-3b9900e494a4

course/urls.py
from django.urls import path
from . import views

app_name="course"

urlpatterns = [
    path('', views.HomeView.as_view(), name="HomeView"),
    path('contact/', views.ContactView.as_view(), name="ContactView"),
    path('about-us/', views.AboutView.as_view(), name="AboutView"),
    path('admin-area/', views.AdminAreaView.as_view(), name="AdminAreaView"),
    path('admin-complain/', views.AdminComplainView.as_view(), name="AdminComplainView"),
    path('admin-warning/', views.AdminWarningView.as_view(), name="AdminWarningView"),
    path('student-area/', views.StudentAreaView.as_view(), name="StudentAreaView"),
    path('instructor-area/', views.InstructorAreaView.as_view(), name="InstructorAreaView"),
    path('manage-class/', views.ManageClassView.as_view(), name="ManageClassView"),
    path('manage-complain/', views.ManageComplainView.as_view(), name="ManageComplainView"),
    path('manage-warning/', views.ManageWarningView.as_view(), name="ManageWarningView"),
    path('create-semester/', views.CreateSemesterView.as_view(), name="CreateSemesterView"),
    path('deactivate-semester/', views.DeavtivateSemesterView.as_view(), name="DeavtivateSemesterView"),
    path('create-class/', views.CreateClassView.as_view(), name="CreateClassView"),
    path('remove-class/', views.RemoveClassView.as_view(), name="RemoveClassView"),
    path('class-detail/', views.CourseDetailView.as_view(), name="CourseDetailView"),
    path('class-detail-instructor/', views.InstructorCourseDetailView.as_view(), name="InstructorCourseDetailView"),
    path('manage-review/', views.ManageReviewView.as_view(), name="ManageReviewView"),
    path('manage-grade/', views.ManageGradeView.as_view(), name="ManageGradeView"),
    path('recieved-warnings/', views.RecievedWarningsView.as_view(), name="RecievedWarningsView"),
    path('classes/', views.StudentCartView.as_view(), name="StudentCartView"),
    path('enroll-requests/', views.EnrollRequestView.as_view(), name="EnrollRequestView"),
]

cunyzero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('course.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>CunyZero</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block ExtraCss %}
    {% endblock ExtraCss %}
</head>

<body>
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

    <header id="main-header">
        <div class="logo-container">
            <img src="{% static 'css/images/logo.png' %}">
            <h3><a href="https://www.cuny.edu/" class="a_no_style">The City University of New York</a> </h3>
        </div>
        {% with request.user.profile.get_warnings as warnings %}
            {% if warnings %}
                <div class="ms-auto circle-warning"><a href="{% url 'course:RecievedWarningsView' %}" class="a_no_style">{{warnings.count}}</a></div>
            {% endif %}
        {% endwith %}
         

        {% comment %} <div class="name-container">
        </div> {% endcomment %}
        {% comment %} <div>
            <h1>Welcome to CunyZero</h1>
        </div> {% endcomment %}
    </header>


<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"><i class="fas fa-bars text-light"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link px-5 active" aria-current="page" href="{% url 'course:HomeView' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-5" href="{% url 'course:AboutView' %}">About Course</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-5" href="{% url 'accounts:ApplyView' %}">Apply</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-5" href="{% url 'course:ContactView' %}">Contact</a>
        </li>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link px-5" href="{% url 'accounts:LogOutView' %}">LogOut</a>
            </li>
        {% else %}
            <li class="nav-item">
            <a class="nav-link px-5" href="{% url 'accounts:HandleSignUp' %}">SignUp</a>
            </li>
            <li class="nav-item">
            <a class="nav-link px-5" href="{% url 'accounts:LogInView' %}">Login</a>
            </li>
        {% endif %}

        {% if request.user.is_staff %}
            <li class="nav-item">
            <a class="nav-link px-5" href="{% url 'course:AdminAreaView' %}">Admin Area</a>
            </li>
            <li class="nav-item">
            <a class="nav-link px-5" href="{% url 'course:AdminComplainView' %}">Complains</a>
            </li>
            <li class="nav-item">
            <a class="nav-link px-5" href="{% url 'course:AdminWarningView' %}">Warnings</a>
            </li>
        {% elif request.user.profile.role == "std" %}
            <li class="nav-item">
                <a class="nav-link px-5" href="{% url 'course:StudentAreaView' %}">Student Area</a>
            </li>
            <li class="nav-item">
                <a class="nav-link px-5" href="{% url 'course:StudentCartView' %}">Classes</a>
            </li>
        {% elif request.user.profile.role == "ins" %}
            <li class="nav-item">
                <a class="nav-link px-5" href="{% url 'course:InstructorAreaView' %}">Instructor Area</a>
            </li>
            <li class="nav-item">
                <a class="nav-link px-5" href="{% url 'course:EnrollRequestView' %}">Enroll Requests</a>
            </li>
        {% endif %}

    </div>
  </div>
</nav>

    {% comment %} <div class="navbar">
        <a href="#home">Home</a>
        <a href="#aboutcourse">About Course</a>
        <a href="#apply">Apply</a>
        <a href="#contact">Contact</a>
        <a href="#signup">Sign Up</a>
        <div class="dropdown">
            <button class="dropbtn">Login
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="Student/student.html">Student</a>
                <a href="Admin/admin.html">Admin</a>
                <a href="Professor/professor.html">Professor</a>
            </div>
        </div>
    </div>
 {% endcomment %}


    {% block content %}
    {% endblock content %}



    <footer>
        <div class="m-container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="social-icons">
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fas fa-file-contract"></i></a></li>

                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="copyright-text">
                        <p>Copyright Fall 2021 Group [S]. | Design: <a rel="nofollow" href="{% url 'course:HomeView' %}" target="_parent">CunyZero</a></p>
                    </div>
                </div>
            </div>
        </div>

    </footer>


<script src="js/fontawesome.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
{% block ExtraJs %}
{% endblock ExtraJs %}
</body>

</html>